name: 'qualifyze_dbt'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  qualifyze_dbt:
    # Configuración de los modelos por capas (Pseudo-Medallion)
    silver:
      +materialized: view
      +schema: silver
    gold:
      +materialized: table
      +schema: gold